"""empty message

Revision ID: 6c04708b7d1d
Revises: 66e9f308ae44
Create Date: 2017-12-12 21:40:35.851909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c04708b7d1d'
down_revision = '66e9f308ae44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('progressions', sa.Column('category', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('progressions', 'category')
    # ### end Alembic commands ###
