"""empty message

Revision ID: ec2f94d6d14f
Revises: 6c04708b7d1d
Create Date: 2018-01-23 00:45:55.583354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec2f94d6d14f'
down_revision = '6c04708b7d1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progressions')
    op.drop_table('plan_days')
    op.drop_table('plan_settings')
    op.drop_table('workoutset_settings')
    op.drop_table('exercise_settings')
    op.add_column('workouts', sa.Column('rest', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'rest')
    op.create_table('exercise_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=64), nullable=True),
    sa.Column('duration_start', sa.NUMERIC(), nullable=True),
    sa.Column('duration_step', sa.NUMERIC(), nullable=True),
    sa.Column('duration_step_interval', sa.NUMERIC(), nullable=True),
    sa.Column('duration_max', sa.NUMERIC(), nullable=True),
    sa.Column('workoutset_setting_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['workoutset_setting_id'], ['workoutset_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workoutset_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('reps_start', sa.INTEGER(), nullable=True),
    sa.Column('reps_step', sa.INTEGER(), nullable=True),
    sa.Column('reps_step_interval', sa.INTEGER(), nullable=True),
    sa.Column('reps_max', sa.INTEGER(), nullable=True),
    sa.Column('progression_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['progression_id'], ['progressions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('distance', sa.VARCHAR(length=64), nullable=True),
    sa.Column('level', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_days',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('plan_setting_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['plan_setting_id'], ['plan_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progressions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('day', sa.INTEGER(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=64), nullable=True),
    sa.Column('warmup', sa.NUMERIC(), nullable=True),
    sa.Column('warmdown', sa.NUMERIC(), nullable=True),
    sa.Column('plan_day_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['plan_day_id'], ['plan_days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
